# Generated by Django 3.0.7 on 2021-02-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('code_block', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=30)),
            ],
        ),
    ]
